# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
