# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160318_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, choices=[('1', 'First Player'), ('2', 'Second Player'), ('3', 'Third Player')], null=True),
        ),
    ]
