# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160320_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.TextField(choices=[('n', 'Not Started'), ('s', 'Started'), ('f', 'Finished'), ('c', 'Cancelled')], default=datetime.datetime(2016, 3, 20, 12, 21, 28, 894414, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
