# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160322_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.TextField(choices=[('n', 'Not Started'), ('s', 'Started'), ('f', 'Finished'), ('c', 'Cancelled')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'First Player'), (2, 'Second Player'), (3, 'Third Player')], null=True),
        ),
    ]
