# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160322_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(blank=True, choices=[(1, 'First Player'), (2, 'Second Player'), (3, 'Third Player')], null=True)),
                ('time', models.IntegerField()),
                ('value', models.IntegerField()),
                ('scoreP1', models.IntegerField(blank=True, null=True)),
                ('scoreP2', models.IntegerField(blank=True, null=True)),
                ('scoreP3', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
    ]
