# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
